### ISSUE TITLE
Update login form to support zulip servers that aren't zulip.com

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#1]
The most important feature missing from the Android app right now is that it currently hardcodes talking to zulip.com.  It should be a pretty straightforward change to have the user type in their server on the login page.

**Comment by willdeed** [comment]
+1 to this. I'm not sure it's that straight forward as there may be UI changes and other use cases to consider when dealing with a connection to a server that's not controlled by Zulip, but it's definitely an important feature from my perspective as well. 

I wish I could help with the coding, but I'm lacking the Android dev skillz.

**Comment by scar45** [comment]
I was tinkering with it tonight, and I was able to get the app building via Gradle in Android Studio after fixing Play Services and commenting out Crashlytics.

I was then able to change the URL that the Android app uses to authenticate against in **ZulipApp.java @ L:126**:

```java
    public String getServerURI() {
//        if (getEmail().equals("iago@zulip.com")) {
//            return "http://10.0.2.2:9991/api/";
//        }
        return "https://MY.SERVER.HERE/";
    }
```

...and when debugging, I see it hit that connection, then (presumably) after my login is validated, it POSTs "v1/fetch_api_key" which returns a 404 error. I dug around the server source and found what I think is the correct API endpoint. Here's what I changed it to in **AsyncLogin.java @ L:31**:

```java
    public final void execute() {
        execute("POST", "api/v1/fetch_api_key");
    }
```

...but it still doesn't appear to work for me. I'm not sure, but I think that URL is looking for the username + API key, instead of the username + password which I think it's being fed. Just shooting in the dark at this point though.

I am not an Android dev by any means, but after getting the server-side working great, I am dying to get the app working! Hope this can help in some way.

**Comment by leoluk** [comment]
Needs a custom Google API key too: https://github.com/zulip/zulip-android/blob/3f58f50112dc6ec1683570f90ee56a78805809bf/src/com/zulip/android/Notifications.java#L21

**Comment by scar45** [comment]
Nice find @leoluk -- I will look into registering a Google API Key. I do have a question about the counterpart in zserver though. I setup Zulip on my own VM using the production tarball. It appears that after editing /etc/zulip/settings.py, the file contents get copied to /home/zulip/deployments/current/zproject/local_settings.py, which is the file above that you referenced. 

In my copy, there is no "GOOGLE_CLIENT_ID" key, so I am hoping that I can disregard the server side API key. I ONLY wish to use e-mail authentication with my private Zulip install, therefore I can forego the "Sign in with Google" functionality which I am assuming would be what this key is used for.

My apologies if this is the wrong place for discussion, but I would be happy to delete/repost this in a better forum if there was one. Otherwise, hoping you can clarify what it would take to get the Android app connecting to our own instances of Zulip. Thanks in advance!

**Comment by leoluk** [comment]
The key is for Google Cloud Messaging, too, which is necessary for push messaging.

**Comment by wolfen351** [comment]
+1 me too, i have some basic android skills, will try work on it in the next few days

**Comment by pkaske** [comment]
+1

**Comment by wolfen351** [comment]
@scar45 How's this one going?

**Comment by scar45** [comment]
@wolfen351 - TBH, life has got really busy for me and I am not sure when (or even if) I'll be able to throw more time at this. I didn't rush into registering a GCM API Key just yet, so that remains, and probably a URL chooser in the form of preferences. I had hardcoded it during testing which of course would need to be changed.

If I do end up getting time, you can bet that I'll clean my code and submit a pull request though, but again, just not sure when!

**Comment by phillipm** [comment]
I found another hard-coded client id at https://github.com/zulip/zulip-android/blob/master/src/com/zulip/android/LoginActivity.java#L164

Must still be missing something because after setting that and the instances mentioned above I still wasn't able to login into a self-hosted Zulip instance on the Android app using Google+

**Comment by wolfen351** [comment]
@phillipm That's great news! My cert is not self signed, so it could theoretically work for me at this point then?

**Comment by casimirextreme** [comment]
For the ssl certificate, you can use free ones like those from https://www.startssl.com/

I'm using it on my zulip instance, it works fine. Just FYI.

**Comment by ff-** [comment]
SSL doesn't work sometimes because of SNI: the Apache Http lib doesn't support it, and in case of virtualhosts the ssl auth fails even if the Certificate is perfectly valid and trusted (such as in case of StartSSL ones).

For this reason trying to make this app work I rewrote the `HTTPRequest` class using the native `HttpURLConnection`, and now SSL works perfectly. @timabbott mind if I open a pull request only for this class? (instead of fixing this entire issue - I made the app work with my Zulip instance, but I'm still figuring out some things)

**Comment by timabbott** [comment]
Yeah @ff-  a pull request that makes progress but doesn't completely solve things is totally welcome

**Comment by ff-** [comment]
@timabbott thanks! I just read in the pull request comments that actually there isn't a "mantainer" doing code reviews on the app; any news on that?

**Comment by zaafar** [comment]
For those android developers seeking to make the android client work for custom server domains. You can bypass the android app login ( username, password or google auth login ) by getting the private API key from settings->show/change your API key (login via web browser) and inserting it manually into the application code. However, custom servers still need to have a valid SSL certificate (i.e. not self-signed).

@timabbott any idea on when the pull requests would merge in the main code? Thanks :)

**Comment by wolfen351** [comment]
@zaafar Is there a way to add this setting (api-key + url) to the settings.xml directly on a rooted phone. I ask because I still want to use the official version if possible?

**Comment by zaafar** [comment]
@wolfen351 TLDR; url=No, api-key=Yes.
As custom server url is hard coded into the application source code, so you need to modify the APK or change the source-code to accept the "custom server" url form a textbox or xml file.

For api-key, yes you can only do that in a rooted phone by adding/updating the value of "api_key" in "/data/data/com.zulip.android/shared_prefs/HumbugActivity.xml". Note: In case the file isn't created, you need to manually create that file.

**Comment by leoluk** [comment]
Someone suggested using SRV records for this: https://github.com/zulip/zulip-desktop/issues/7

I think it's a great idea.

**Comment by wolfen351** [comment]
I agree, think the DNS solution is the most scalable and elegant

**Comment by casdr** [comment]
Any update on this? The app is pretty useless for new accounts now.

**Comment by ryansnowboarder** [comment]
I'm trying to fix some things on the Android app and I'm hitting a wall while logging in. How do I do that (requires a @zulip.com login)?

**Comment by niftynei** [comment]
This has been mostly resolved as of #52 .  There's still a bit to be worked out to allow G+ authentication for non-Zulip domains.  I'll open a new issue to track that last piece of work separately.  

This functionality will be released in the next app version. :)

**Comment by niftynei** [comment]
Update: see issue #64

**Comment by brainwane** [comment]
The beta channel app does have this feature. You can join the Zulip app's beta channel at https://play.google.com/apps/testing/com.zulip.android , after which the Play store should auto-update you.

**Comment by timabbott** [comment]
Just a quick update, this feature is now available in the Play Store Android app.  

Note that https://github.com/zulip/zulip-android/issues/64 is still open (i.e. Google auth and GCM still don't work with non-zulip.com servers, due to technical issues with how GCM/Google Auth for Android work).

**Comment by willdeed** [comment]
Cheers, Tim!
