### ISSUE TITLE
Clear topic expansion in streams drawer when unnarrowing/renarrowing

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#106]
Currently, after a user narrows to a bunch of streams, the streams drawer leaks all of the topic lists being open, which obscures the list of streams available to narrow to.

**Comment by kunall17** [comment]
@timabbott If this issue is fixed please close this one.
Commit c88df64 allows only 1 stream to be expanded at a time previous one is collapsed on opening a new one.
I hope this fixes the issue.

Btw I didn't know writing `"Fixes #123" ` in the commit messages auto closes the issues, I have started writing them now, will have to post messages in the issue's which have been solved but are still opened.

**Comment by timabbott** [comment]
Agreed, I think that is a fix for this bug.  And yeah, the `Fixes: #123` syntax is super useful for this sort of thing :)
