### ISSUE TITLE
Server flooded, returns 500

### ISSUE THREAD

**Issue by ff-** [zulip/zulip-android#14]
When the app connects to the server it starts flooding it with requests - then the server enters in rate limiting mode, and returns `Internal Server Error`, making the app impossible to use (for example it is impossible to send messages).

**Comment by ff-** [comment]
Further investigating on this, it seems that the application polls the APIs (without even a Timeout) in `AsyncGetEvents.run()`. 

And maybe this happens because a self hosted server doesn't (always) have a GCM id. 
Since we do already have a RabbitMQ instance running, could it be worth to use [RabbitMQ for push notifications](http://stackoverflow.com/questions/24404993/google-cloud-messaging-vs-rabbitmq) too, instead of polling?

**Comment by timabbott** [comment]
In theory that function should be using exponential backoff in the event it gets an error:
https://github.com/zulip/zulip-android/blob/master/src/com/zulip/android/AsyncGetEvents.java#L54
So I think the problem is not that we're polling but that there's an error handling case there that isn't working properly.

**Comment by niftynei** [comment]
As part of the move to OkHttp #69 , we added a wait to the run loop so that the server doesn't get flooded. 

https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/networking/AsyncGetEvents.java#L167
