### ISSUE TITLE
Clicking on a stream link doesn't redirect to most recent message or last unread message.

### ISSUE THREAD

**Issue by 540KJ** [zulip/zulip-android#301]
After pressing on a stream link, through the stream list or through the stream link on a message, I am taken  
to a message significantly older than the most recent, I would of expected it to take me to the last unread message or the most recent message.

## Example from electron stream:
**Where it takes me:**
<img src="https://cloud.githubusercontent.com/assets/23611943/21961085/b36acdec-db54-11e6-9386-5cbe7d4630fe.png" width="225" height="400" />
**Where it should take me:**
<img src="https://cloud.githubusercontent.com/assets/23611943/21961086/b36da792-db54-11e6-824d-a81b293c8b8c.png" width="225" height="400" />

**Comment by vishwesh3** [comment]
I think this is due to read unread attribute of messages. Will look into this and create PR soon. If there are many unread messages and user opens app it will be better to show dialog like this
![screenshot_20170115-133725_1](https://cloud.githubusercontent.com/assets/18511177/21961172/91b6f4fe-db28-11e6-9cec-63f5354ae9d0.jpg)

**Comment by Sam1301** [comment]
Hi @vishwesh3, I think I have already worked on this https://github.com/zulip/zulip-android/pull/279/commits/f4ce5f26fa57780293d036a078de36207ff4b13d.

**Comment by anuradhagupta345** [comment]
@Sam1301 Shall I give it a try?

**Comment by kunall17** [comment]
@anuradhagupta345 sam1301 has already built this one https://github.com/zulip/zulip-android/pull/279

**Comment by kunall17** [comment]
Fixed via #279
