### ISSUE TITLE
remove topic indicator for new messages in same topic

### ISSUE THREAD

**Issue by vbNETonIce** [zulip/zulip-android#441]
**Actual Behaviour**
This topic indicator/separator appears even when user is already in that topic (not in home) and replies to a message. That gives the impression that one is still in home thread or the text above the indication belongs to a different topic. 
Also; three times "android review" on the same page doesn't need to be. 
![20170304_22-00-58_paintdotnet](https://cloud.githubusercontent.com/assets/26190934/23582230/19f49bfa-0126-11e7-8471-f7e7482d23e6.png)

**Expected Behaviour**
The indicator doesn't show up for new messages when user has one topic opened and replies to it.

**Comment by prati0100** [comment]
I'd like to work on this. Can anyone point me to where I should start looking for this.

@zulipbot claim-issue

**Comment by vishwesh3** [comment]
One simple approach:-

Add a  parameter `is instance of TopicFilter` here https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/activities/RecyclerMessageAdapter.java#L97

you can check here https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/activities/MessageListFragment.java#L113 
if `filter instance of NarrowFilterStream && subject!=null`

and You have to check here https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/activities/RecyclerMessageAdapter.java#L291 and https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/activities/RecyclerMessageAdapter.java#L262 

if current filter is topicFilter then no need to add `MessageParent` else add 

You can play around code and find others approaches too

**Comment by abdulwd** [comment]
Is this issue resolved?

**Comment by prati0100** [comment]
@abdulwd Yeah, I'm almost done. I'll create a PR tomorrow.

**Comment by prati0100** [comment]
Okay, so I tried a fix but that produces some bugs elsewhere so I'm not gonna push that. I tried to find where the problem is. Here's what I found:

The method `addNewMessage()` (in RecyclerMessageAdapter.java, line 290) is called when a new message arrives. If the view is narrowed to a stream, it should only show the number of messages in that stream or topic when `getItemCount(false)` is called. Instead, the value that it returns is the total number of messages in the entire server. Then somehow this same method is called again and then the value that `getItemCount(false)` returns is the number of messages in that topic. I tested this by adding a log line at the start if the method, that logs the value of `getItemCount(false)`.

What I don't get is why the value of `getItemCount(false)` is incorrect at first and why this method is called twice, once where the value is correct and once when it is incorrect. As far as I could understand, `MessageListFragment`'s `onMessages()` method calls `addNewMessage()` only once.

Any ideas what is going on here @vishwesh3

**Comment by vishwesh3** [comment]
@prati0100 We have fragments for each view. When app launches `homeList` fragment is set. And on narrow `homeList` fragment is pushed into the stack and another fragment `narrowedList` is set. 

Now whenever new message  arrives  [onNewMessages](https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/activities/ZulipActivity.java#L2584) is called from `ZulipActivity` and then messages are added in `homeList` (homeView) and `narrowedList` (if user is narrowed) ([from here](https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/activities/ZulipActivity.java#L2585)) 

Now `onNewMessages` is called [here](https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/activities/MessageListFragment.java#L630) in each fragment (homeList and narrowedList)

**Comment by kunall17** [comment]
Thanks for reporting this @vbNETonIce and has been fixed by #477
