### ISSUE TITLE
Status not updated "Unknown error"

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-android#454]
[Read our guide on bug reports here](./ISSUES_GUIDE.md)

**Actual Behaviour**

Currently status is not updated. Toast is showing **Unknown error**
![screenshot_20170309-145028](https://cloud.githubusercontent.com/assets/18511177/23745601/c5c73044-04de-11e7-89a9-ae74be802d50.jpg)

**Expected Behaviour**

Status should update.

**Reason/error**

`org.json.JSONException: No value for client` caught here
https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/networking/AsyncStatusUpdate.java#L147

Currently [here](https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/networking/AsyncStatusUpdate.java#L53) we are iterating over all Platforms (website, ZulipAndroid, ZulipIos etc) to find LatestPresence.

When I observed response, found that one object is 

`
 "alain.poirier1@gmail.com": {
      "website": {
        "status": "active",
        "timestamp": 1469846885,
        "client": "website",
        "pushable": false
      },
      "aggregated": {
        "status": "active",
        "timestamp": 1475662120
      },
      "ZulipiOS": {
        "status": "active",
        "timestamp": 1475662120,
        "client": "ZulipiOS",
        "pushable": false
      }
    },
`

passing this object in [chooseLatestPresence](https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/networking/AsyncStatusUpdate.java#L113) will return 

`
 "aggregated": {
        "status": "active",
        "timestamp": 1475662120
      },
`

as [latestPresenceObj](https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/networking/AsyncStatusUpdate.java#L113)

which doesn't have [client](https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/networking/AsyncStatusUpdate.java#L120) and finally causing `JSONException`

**Would you like to work on the issue?**

Yes

**Comment by vishwesh3** [comment]
@zulipbot claim

**Comment by Sam1301** [comment]
So this is due to a recent change in the server. @timabbott thoughts on this?

**Comment by timabbott** [comment]
Hrm, yeah, this was an API change in the server designed to support another use case (with the side effect of making this sort of thing a lot easier to do, where clients wouldn't need to iterate through every client).  

I think it's probably a bug that no client is listed in the aggregated response, since one might reasonably want to know what the latest one's client was without parsing them all.  So we should treat this as a server bug and fix quickly (I think it only impacts chat.zulip.org right now but that will change!).

@kkanahin can you submit a PR adding `client` to the aggregated list ASAP?

**Comment by timabbott** [comment]
Merged the server fix, so hopefully this should be good once I deploy to chat.zulip.org (should be tonight).
