### ISSUE TITLE
New private message is unavailable to read

### ISSUE THREAD

**Issue by winmasta** [zulip/zulip-android#520]
[Read our guide on bug reports here](./ISSUES_GUIDE.md)

**Actual Behaviour**

When I got new private message I open chat and can see New message but when I try to reach it by scrolling down I can't see it in chat flow. Message becomes available much later, I can't check any dependoncies about it.

**Expected Behaviour**

Expected to see new message in chat flow as soon as it was recieved.

**Would you like to work on the issue?**

No.

**Comment by timabbott** [comment]
@winmasta you're almost certainly using https://github.com/zulip/zulip-mobile/issues, not this old project.  In any case, that specific issue is known and will be fixed in a release in the next few days.  Sorry for the confusion!  I've updated the issue template for this project to make clear what's going on for future folks.
